//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
namespace EmployeeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTable
    {
        public int EmployeeId { get; set; }
        [Required(ErrorMessage ="Employee Name is required!")]
        [StringLength(20,MinimumLength =3)]
        public string Name { get; set; }
        public Nullable<long> Salary { get; set; }
        [Required(ErrorMessage ="Please enter Department no. of the employee!")]
        public Nullable<int> DepartmentId { get; set; }
        public string TokenNumber { get; set; }
    }
}
